// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oceanbook.proto

package oceanbookpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order_Side int32

const (
	Order_ASK Order_Side = 0
	Order_BID Order_Side = 1
)

var Order_Side_name = map[int32]string{
	0: "ASK",
	1: "BID",
}

var Order_Side_value = map[string]int32{
	"ASK": 0,
	"BID": 1,
}

func (x Order_Side) String() string {
	return proto.EnumName(Order_Side_name, int32(x))
}

func (Order_Side) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3544f9578582e495, []int{0, 0}
}

type Order_State int32

const (
	Order_PENDING   Order_State = 0
	Order_FILLED    Order_State = 1
	Order_CANCELLED Order_State = 2
)

var Order_State_name = map[int32]string{
	0: "PENDING",
	1: "FILLED",
	2: "CANCELLED",
}

var Order_State_value = map[string]int32{
	"PENDING":   0,
	"FILLED":    1,
	"CANCELLED": 2,
}

func (x Order_State) String() string {
	return proto.EnumName(Order_State_name, int32(x))
}

func (Order_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3544f9578582e495, []int{0, 1}
}

type Order struct {
	Id                   uint64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                string      `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             string      `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Side                 Order_Side  `protobuf:"varint,4,opt,name=side,proto3,enum=oceanbook.Order_Side" json:"side,omitempty"`
	Symbol               string      `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	State                Order_State `protobuf:"varint,6,opt,name=state,proto3,enum=oceanbook.Order_State" json:"state,omitempty"`
	StopPrice            string      `protobuf:"bytes,7,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	ImmediateOrCancel    bool        `protobuf:"varint,8,opt,name=immediate_or_cancel,json=immediateOrCancel,proto3" json:"immediate_or_cancel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_3544f9578582e495, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Order) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *Order) GetSide() Order_Side {
	if m != nil {
		return m.Side
	}
	return Order_ASK
}

func (m *Order) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Order) GetState() Order_State {
	if m != nil {
		return m.State
	}
	return Order_PENDING
}

func (m *Order) GetStopPrice() string {
	if m != nil {
		return m.StopPrice
	}
	return ""
}

func (m *Order) GetImmediateOrCancel() bool {
	if m != nil {
		return m.ImmediateOrCancel
	}
	return false
}

type Trade struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol               string               `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price                string               `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             string               `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TakerId              uint64               `protobuf:"varint,5,opt,name=taker_id,json=takerId,proto3" json:"taker_id,omitempty"`
	MakerId              uint64               `protobuf:"varint,6,opt,name=maker_id,json=makerId,proto3" json:"maker_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_3544f9578582e495, []int{1}
}

func (m *Trade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trade.Unmarshal(m, b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
}
func (m *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(m, src)
}
func (m *Trade) XXX_Size() int {
	return xxx_messageInfo_Trade.Size(m)
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Trade) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Trade) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Trade) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *Trade) GetTakerId() uint64 {
	if m != nil {
		return m.TakerId
	}
	return 0
}

func (m *Trade) GetMakerId() uint64 {
	if m != nil {
		return m.MakerId
	}
	return 0
}

func (m *Trade) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type InsertOrderRequest struct {
	Id                   uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                string     `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             string     `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Side                 Order_Side `protobuf:"varint,4,opt,name=side,proto3,enum=oceanbook.Order_Side" json:"side,omitempty"`
	Symbol               string     `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	StopPrice            string     `protobuf:"bytes,6,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	ImmediateOrCancel    bool       `protobuf:"varint,7,opt,name=immediate_or_cancel,json=immediateOrCancel,proto3" json:"immediate_or_cancel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InsertOrderRequest) Reset()         { *m = InsertOrderRequest{} }
func (m *InsertOrderRequest) String() string { return proto.CompactTextString(m) }
func (*InsertOrderRequest) ProtoMessage()    {}
func (*InsertOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3544f9578582e495, []int{2}
}

func (m *InsertOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertOrderRequest.Unmarshal(m, b)
}
func (m *InsertOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertOrderRequest.Marshal(b, m, deterministic)
}
func (m *InsertOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertOrderRequest.Merge(m, src)
}
func (m *InsertOrderRequest) XXX_Size() int {
	return xxx_messageInfo_InsertOrderRequest.Size(m)
}
func (m *InsertOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertOrderRequest proto.InternalMessageInfo

func (m *InsertOrderRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertOrderRequest) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *InsertOrderRequest) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *InsertOrderRequest) GetSide() Order_Side {
	if m != nil {
		return m.Side
	}
	return Order_ASK
}

func (m *InsertOrderRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *InsertOrderRequest) GetStopPrice() string {
	if m != nil {
		return m.StopPrice
	}
	return ""
}

func (m *InsertOrderRequest) GetImmediateOrCancel() bool {
	if m != nil {
		return m.ImmediateOrCancel
	}
	return false
}

type CancelOrderRequest struct {
	OrderId              uint64   `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderRequest) Reset()         { *m = CancelOrderRequest{} }
func (m *CancelOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CancelOrderRequest) ProtoMessage()    {}
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3544f9578582e495, []int{3}
}

func (m *CancelOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderRequest.Unmarshal(m, b)
}
func (m *CancelOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderRequest.Marshal(b, m, deterministic)
}
func (m *CancelOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderRequest.Merge(m, src)
}
func (m *CancelOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CancelOrderRequest.Size(m)
}
func (m *CancelOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderRequest proto.InternalMessageInfo

func (m *CancelOrderRequest) GetOrderId() uint64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *CancelOrderRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type CancelOrderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderResponse) Reset()         { *m = CancelOrderResponse{} }
func (m *CancelOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CancelOrderResponse) ProtoMessage()    {}
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3544f9578582e495, []int{4}
}

func (m *CancelOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderResponse.Unmarshal(m, b)
}
func (m *CancelOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderResponse.Marshal(b, m, deterministic)
}
func (m *CancelOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderResponse.Merge(m, src)
}
func (m *CancelOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CancelOrderResponse.Size(m)
}
func (m *CancelOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderResponse proto.InternalMessageInfo

type NewOrderBookRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewOrderBookRequest) Reset()         { *m = NewOrderBookRequest{} }
func (m *NewOrderBookRequest) String() string { return proto.CompactTextString(m) }
func (*NewOrderBookRequest) ProtoMessage()    {}
func (*NewOrderBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3544f9578582e495, []int{5}
}

func (m *NewOrderBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewOrderBookRequest.Unmarshal(m, b)
}
func (m *NewOrderBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewOrderBookRequest.Marshal(b, m, deterministic)
}
func (m *NewOrderBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewOrderBookRequest.Merge(m, src)
}
func (m *NewOrderBookRequest) XXX_Size() int {
	return xxx_messageInfo_NewOrderBookRequest.Size(m)
}
func (m *NewOrderBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewOrderBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewOrderBookRequest proto.InternalMessageInfo

func (m *NewOrderBookRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type NewOrderBookResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewOrderBookResponse) Reset()         { *m = NewOrderBookResponse{} }
func (m *NewOrderBookResponse) String() string { return proto.CompactTextString(m) }
func (*NewOrderBookResponse) ProtoMessage()    {}
func (*NewOrderBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3544f9578582e495, []int{6}
}

func (m *NewOrderBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewOrderBookResponse.Unmarshal(m, b)
}
func (m *NewOrderBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewOrderBookResponse.Marshal(b, m, deterministic)
}
func (m *NewOrderBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewOrderBookResponse.Merge(m, src)
}
func (m *NewOrderBookResponse) XXX_Size() int {
	return xxx_messageInfo_NewOrderBookResponse.Size(m)
}
func (m *NewOrderBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewOrderBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewOrderBookResponse proto.InternalMessageInfo

type GetDepthRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDepthRequest) Reset()         { *m = GetDepthRequest{} }
func (m *GetDepthRequest) String() string { return proto.CompactTextString(m) }
func (*GetDepthRequest) ProtoMessage()    {}
func (*GetDepthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3544f9578582e495, []int{7}
}

func (m *GetDepthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDepthRequest.Unmarshal(m, b)
}
func (m *GetDepthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDepthRequest.Marshal(b, m, deterministic)
}
func (m *GetDepthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDepthRequest.Merge(m, src)
}
func (m *GetDepthRequest) XXX_Size() int {
	return xxx_messageInfo_GetDepthRequest.Size(m)
}
func (m *GetDepthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDepthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDepthRequest proto.InternalMessageInfo

func (m *GetDepthRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type PriceLevel struct {
	Price                string   `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             string   `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrdersCount          uint64   `protobuf:"varint,3,opt,name=orders_count,json=ordersCount,proto3" json:"orders_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceLevel) Reset()         { *m = PriceLevel{} }
func (m *PriceLevel) String() string { return proto.CompactTextString(m) }
func (*PriceLevel) ProtoMessage()    {}
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_3544f9578582e495, []int{8}
}

func (m *PriceLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceLevel.Unmarshal(m, b)
}
func (m *PriceLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceLevel.Marshal(b, m, deterministic)
}
func (m *PriceLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceLevel.Merge(m, src)
}
func (m *PriceLevel) XXX_Size() int {
	return xxx_messageInfo_PriceLevel.Size(m)
}
func (m *PriceLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceLevel.DiscardUnknown(m)
}

var xxx_messageInfo_PriceLevel proto.InternalMessageInfo

func (m *PriceLevel) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *PriceLevel) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *PriceLevel) GetOrdersCount() uint64 {
	if m != nil {
		return m.OrdersCount
	}
	return 0
}

type Depth struct {
	Symbol               string        `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bids                 []*PriceLevel `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks                 []*PriceLevel `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Depth) Reset()         { *m = Depth{} }
func (m *Depth) String() string { return proto.CompactTextString(m) }
func (*Depth) ProtoMessage()    {}
func (*Depth) Descriptor() ([]byte, []int) {
	return fileDescriptor_3544f9578582e495, []int{9}
}

func (m *Depth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Depth.Unmarshal(m, b)
}
func (m *Depth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Depth.Marshal(b, m, deterministic)
}
func (m *Depth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Depth.Merge(m, src)
}
func (m *Depth) XXX_Size() int {
	return xxx_messageInfo_Depth.Size(m)
}
func (m *Depth) XXX_DiscardUnknown() {
	xxx_messageInfo_Depth.DiscardUnknown(m)
}

var xxx_messageInfo_Depth proto.InternalMessageInfo

func (m *Depth) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Depth) GetBids() []*PriceLevel {
	if m != nil {
		return m.Bids
	}
	return nil
}

func (m *Depth) GetAsks() []*PriceLevel {
	if m != nil {
		return m.Asks
	}
	return nil
}

func init() {
	proto.RegisterEnum("oceanbook.Order_Side", Order_Side_name, Order_Side_value)
	proto.RegisterEnum("oceanbook.Order_State", Order_State_name, Order_State_value)
	proto.RegisterType((*Order)(nil), "oceanbook.Order")
	proto.RegisterType((*Trade)(nil), "oceanbook.Trade")
	proto.RegisterType((*InsertOrderRequest)(nil), "oceanbook.InsertOrderRequest")
	proto.RegisterType((*CancelOrderRequest)(nil), "oceanbook.CancelOrderRequest")
	proto.RegisterType((*CancelOrderResponse)(nil), "oceanbook.CancelOrderResponse")
	proto.RegisterType((*NewOrderBookRequest)(nil), "oceanbook.NewOrderBookRequest")
	proto.RegisterType((*NewOrderBookResponse)(nil), "oceanbook.NewOrderBookResponse")
	proto.RegisterType((*GetDepthRequest)(nil), "oceanbook.GetDepthRequest")
	proto.RegisterType((*PriceLevel)(nil), "oceanbook.PriceLevel")
	proto.RegisterType((*Depth)(nil), "oceanbook.Depth")
}

func init() { proto.RegisterFile("oceanbook.proto", fileDescriptor_3544f9578582e495) }

var fileDescriptor_3544f9578582e495 = []byte{
	// 687 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x8d, 0x9d, 0xf7, 0x4d, 0x69, 0xc3, 0xf4, 0x21, 0x37, 0x52, 0x4b, 0xf0, 0x2a, 0x95, 0xa8,
	0x83, 0xca, 0x8a, 0x87, 0x90, 0x9a, 0xa4, 0x54, 0x11, 0x55, 0x5a, 0xdc, 0xae, 0xd8, 0x44, 0x63,
	0xfb, 0x92, 0x5a, 0x89, 0x3d, 0xae, 0x67, 0x52, 0xd4, 0x9f, 0xe2, 0x63, 0x10, 0x1f, 0xc1, 0x67,
	0x20, 0x8f, 0x13, 0xc7, 0x6e, 0x30, 0xb0, 0x64, 0xe7, 0x3b, 0xe7, 0xf8, 0xcc, 0xbd, 0xe7, 0x9e,
	0xc4, 0xb0, 0xc5, 0x6c, 0xa4, 0xbe, 0xc5, 0xd8, 0xd4, 0x08, 0x42, 0x26, 0x18, 0xa9, 0x27, 0x07,
	0xad, 0xb7, 0x13, 0x57, 0xdc, 0xce, 0x2d, 0xc3, 0x66, 0x5e, 0x77, 0xc2, 0x66, 0xd4, 0x9f, 0x74,
	0x25, 0xc7, 0x9a, 0x7f, 0xe9, 0x06, 0xe2, 0x21, 0x40, 0xde, 0x15, 0xae, 0x87, 0x5c, 0x50, 0x2f,
	0x58, 0x3d, 0xc5, 0x3a, 0xfa, 0x0f, 0x15, 0xca, 0x97, 0xa1, 0x83, 0x21, 0xd9, 0x04, 0xd5, 0x75,
	0x34, 0xa5, 0xad, 0x74, 0x4a, 0xa6, 0xea, 0x3a, 0x64, 0x07, 0xca, 0x41, 0xe8, 0xda, 0xa8, 0xa9,
	0x6d, 0xa5, 0x53, 0x37, 0xe3, 0x82, 0xb4, 0xa0, 0x76, 0x37, 0xa7, 0xbe, 0x70, 0xc5, 0x83, 0x56,
	0x94, 0x40, 0x52, 0x93, 0x23, 0x28, 0x71, 0xd7, 0x41, 0xad, 0xd4, 0x56, 0x3a, 0x9b, 0x27, 0xbb,
	0xc6, 0xaa, 0x67, 0x79, 0x83, 0x71, 0xed, 0x3a, 0x68, 0x4a, 0x0a, 0xd9, 0x83, 0x0a, 0x7f, 0xf0,
	0x2c, 0x36, 0xd3, 0xca, 0x52, 0x64, 0x51, 0x91, 0x17, 0x50, 0xe6, 0x82, 0x0a, 0xd4, 0x2a, 0x52,
	0x63, 0x6f, 0x5d, 0x23, 0x42, 0xcd, 0x98, 0x44, 0x0e, 0x00, 0xb8, 0x60, 0xc1, 0x38, 0xee, 0xb3,
	0x2a, 0x95, 0xea, 0xd1, 0xc9, 0x95, 0xec, 0xd5, 0x80, 0x6d, 0xd7, 0xf3, 0xd0, 0x71, 0xa9, 0xc0,
	0x31, 0x0b, 0xc7, 0x36, 0xf5, 0x6d, 0x9c, 0x69, 0xb5, 0xb6, 0xd2, 0xa9, 0x99, 0x4f, 0x13, 0xe8,
	0x32, 0xec, 0x4b, 0x40, 0xd7, 0xa0, 0x14, 0xb5, 0x48, 0xaa, 0x50, 0x3c, 0xbd, 0xfe, 0xd8, 0x2c,
	0x44, 0x0f, 0xbd, 0xe1, 0xa0, 0xa9, 0xe8, 0x5d, 0x28, 0xcb, 0x8b, 0x49, 0x03, 0xaa, 0x57, 0x67,
	0xa3, 0xc1, 0x70, 0x74, 0xde, 0x2c, 0x10, 0x80, 0xca, 0x87, 0xe1, 0xc5, 0xc5, 0xd9, 0xa0, 0xa9,
	0x90, 0x27, 0x50, 0xef, 0x9f, 0x8e, 0xfa, 0x67, 0xb2, 0x54, 0xf5, 0xef, 0x0a, 0x94, 0x6f, 0x42,
	0xea, 0xe0, 0x9a, 0xad, 0xab, 0xc9, 0xd5, 0xcc, 0xe4, 0x89, 0xdd, 0xc5, 0x3c, 0xbb, 0x4b, 0x8f,
	0xec, 0xde, 0x87, 0x9a, 0xa0, 0x53, 0x0c, 0xc7, 0xae, 0x23, 0x5d, 0x2c, 0x99, 0x55, 0x59, 0x0f,
	0x9d, 0x08, 0xf2, 0x96, 0x50, 0x25, 0x86, 0xbc, 0x05, 0xf4, 0x1a, 0xc0, 0x0e, 0x91, 0x0a, 0x74,
	0xc6, 0x54, 0x48, 0xcf, 0x1a, 0x27, 0x2d, 0x63, 0xc2, 0xd8, 0x64, 0x86, 0xc6, 0x32, 0x37, 0xc6,
	0xcd, 0x32, 0x26, 0x66, 0x7d, 0xc1, 0x3e, 0x15, 0xfa, 0x4f, 0x05, 0xc8, 0xd0, 0xe7, 0x18, 0x0a,
	0xb9, 0x0b, 0x13, 0xef, 0xe6, 0xc8, 0xc5, 0xff, 0x11, 0x9c, 0x6c, 0x14, 0x2a, 0xff, 0x18, 0x85,
	0x6a, 0x5e, 0x14, 0xce, 0x81, 0xc4, 0x4f, 0x99, 0x49, 0xf7, 0xa1, 0xc6, 0xa2, 0x7a, 0x9c, 0xcc,
	0x5b, 0x95, 0xf5, 0x30, 0x77, 0xad, 0xfa, 0x2e, 0x6c, 0x67, 0x84, 0x78, 0xc0, 0x7c, 0x8e, 0xfa,
	0x31, 0x6c, 0x8f, 0xf0, 0xab, 0x3c, 0xeb, 0x31, 0x36, 0x5d, 0x5e, 0xb0, 0x52, 0x51, 0x32, 0x2a,
	0x7b, 0xb0, 0x93, 0xa5, 0x2f, 0x64, 0x8e, 0x60, 0xeb, 0x1c, 0xc5, 0x00, 0x03, 0x71, 0xfb, 0x37,
	0x09, 0x0a, 0x20, 0xad, 0xb8, 0xc0, 0x7b, 0x4c, 0xa5, 0x4d, 0xc9, 0xdb, 0x91, 0xfa, 0x68, 0x47,
	0xcf, 0x61, 0x43, 0xce, 0xca, 0xc7, 0x36, 0x9b, 0xfb, 0x42, 0xee, 0xb0, 0x64, 0x36, 0xe2, 0xb3,
	0x7e, 0x74, 0xa4, 0xcf, 0xa1, 0x2c, 0x5b, 0xc9, 0xeb, 0x21, 0xda, 0xb3, 0xe5, 0x3a, 0x5c, 0x53,
	0xdb, 0xc5, 0x4e, 0x23, 0xb3, 0xe7, 0x55, 0x6b, 0xa6, 0xa4, 0x44, 0x54, 0xca, 0xa7, 0x5c, 0x2b,
	0xfe, 0x91, 0x1a, 0x51, 0x4e, 0xbe, 0xa9, 0x50, 0xbf, 0x5c, 0xc2, 0xe4, 0x13, 0x6c, 0xa4, 0xad,
	0x22, 0x87, 0xa9, 0x57, 0x7f, 0x63, 0x79, 0xeb, 0x59, 0x2e, 0xbe, 0xf0, 0xb8, 0x40, 0x7a, 0xd0,
	0x48, 0xc5, 0x9e, 0x1c, 0xa4, 0xde, 0x58, 0xff, 0x39, 0xb4, 0x9a, 0x29, 0x58, 0xfe, 0x05, 0xe8,
	0x85, 0x97, 0x0a, 0x19, 0x41, 0x23, 0x95, 0x83, 0x8c, 0xc6, 0x7a, 0xd0, 0x5a, 0x87, 0x79, 0x70,
	0xd2, 0xd3, 0x1b, 0xa8, 0x2d, 0x37, 0x4f, 0x5a, 0x29, 0xf6, 0xa3, 0x38, 0x64, 0xba, 0x91, 0x80,
	0x5e, 0xe8, 0xbd, 0xff, 0xfc, 0x2e, 0xf5, 0xc9, 0x70, 0x42, 0x7a, 0x8f, 0x3e, 0x72, 0xde, 0x4d,
	0x98, 0x5d, 0x1a, 0xb8, 0xc9, 0x37, 0xe4, 0x98, 0x07, 0x68, 0xaf, 0xb0, 0xc0, 0xb2, 0x2a, 0x12,
	0x7a, 0xf5, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x89, 0xaf, 0xb2, 0x95, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OceanbookClient is the client API for Oceanbook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OceanbookClient interface {
	NewOrderBook(ctx context.Context, in *NewOrderBookRequest, opts ...grpc.CallOption) (*NewOrderBookResponse, error)
	InsertOrder(ctx context.Context, in *InsertOrderRequest, opts ...grpc.CallOption) (Oceanbook_InsertOrderClient, error)
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	GetDepth(ctx context.Context, in *GetDepthRequest, opts ...grpc.CallOption) (*Depth, error)
}

type oceanbookClient struct {
	cc *grpc.ClientConn
}

func NewOceanbookClient(cc *grpc.ClientConn) OceanbookClient {
	return &oceanbookClient{cc}
}

func (c *oceanbookClient) NewOrderBook(ctx context.Context, in *NewOrderBookRequest, opts ...grpc.CallOption) (*NewOrderBookResponse, error) {
	out := new(NewOrderBookResponse)
	err := c.cc.Invoke(ctx, "/oceanbook.Oceanbook/NewOrderBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oceanbookClient) InsertOrder(ctx context.Context, in *InsertOrderRequest, opts ...grpc.CallOption) (Oceanbook_InsertOrderClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Oceanbook_serviceDesc.Streams[0], "/oceanbook.Oceanbook/InsertOrder", opts...)
	if err != nil {
		return nil, err
	}
	x := &oceanbookInsertOrderClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Oceanbook_InsertOrderClient interface {
	Recv() (*Trade, error)
	grpc.ClientStream
}

type oceanbookInsertOrderClient struct {
	grpc.ClientStream
}

func (x *oceanbookInsertOrderClient) Recv() (*Trade, error) {
	m := new(Trade)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *oceanbookClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, "/oceanbook.Oceanbook/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oceanbookClient) GetDepth(ctx context.Context, in *GetDepthRequest, opts ...grpc.CallOption) (*Depth, error) {
	out := new(Depth)
	err := c.cc.Invoke(ctx, "/oceanbook.Oceanbook/GetDepth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OceanbookServer is the server API for Oceanbook service.
type OceanbookServer interface {
	NewOrderBook(context.Context, *NewOrderBookRequest) (*NewOrderBookResponse, error)
	InsertOrder(*InsertOrderRequest, Oceanbook_InsertOrderServer) error
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	GetDepth(context.Context, *GetDepthRequest) (*Depth, error)
}

func RegisterOceanbookServer(s *grpc.Server, srv OceanbookServer) {
	s.RegisterService(&_Oceanbook_serviceDesc, srv)
}

func _Oceanbook_NewOrderBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewOrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OceanbookServer).NewOrderBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oceanbook.Oceanbook/NewOrderBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OceanbookServer).NewOrderBook(ctx, req.(*NewOrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oceanbook_InsertOrder_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InsertOrderRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OceanbookServer).InsertOrder(m, &oceanbookInsertOrderServer{stream})
}

type Oceanbook_InsertOrderServer interface {
	Send(*Trade) error
	grpc.ServerStream
}

type oceanbookInsertOrderServer struct {
	grpc.ServerStream
}

func (x *oceanbookInsertOrderServer) Send(m *Trade) error {
	return x.ServerStream.SendMsg(m)
}

func _Oceanbook_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OceanbookServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oceanbook.Oceanbook/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OceanbookServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oceanbook_GetDepth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OceanbookServer).GetDepth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oceanbook.Oceanbook/GetDepth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OceanbookServer).GetDepth(ctx, req.(*GetDepthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Oceanbook_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oceanbook.Oceanbook",
	HandlerType: (*OceanbookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewOrderBook",
			Handler:    _Oceanbook_NewOrderBook_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _Oceanbook_CancelOrder_Handler,
		},
		{
			MethodName: "GetDepth",
			Handler:    _Oceanbook_GetDepth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InsertOrder",
			Handler:       _Oceanbook_InsertOrder_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "oceanbook.proto",
}
